### ISSUE TITLE
Hello, is it possible not to install yt-dlp, ffmpeg and ffprobe automatically when this program is being installed?

### ISSUE THREAD

**Issue by MRDHR** [ybd-project/node-fluent-ytdlp#1]
## 前提

- この報告が**まだIssuesにない**ことを確認しています。 =>
is it possible not to install yt-dlp, ffmpeg and ffprobe automatically when this program is being installed?
## 詳細
Personally, I prefer to install yt-dlp and ffmpeg manually. Currently, yt-dlp and ffmpeg are compiled when the program is being installed, and there are always errors in the compilation process. Unable to install successfully.

**Comment by ybd-project** [comment]
Yes, it is possible to disable automatic downloads.
But the strength of this API is that it can automatically download yt-dlp, ffmpeg, etc.
Therefore, when installing a package, you can display a message asking if you want to download yt-dlp, etc., and only download them if you select "yes".

Please note that this text is written using a translator, so the text may be incorrect.

**Comment by MRDHR** [comment]
But when I install with the npm install node-fluent-ytdlp command, there is always automatic installation of yt-dlp, ffmpeg, and ffprobe. Npm did not prompt me whether to install

![image](https://github.com/ybd-project/node-fluent-ytdlp/assets/5576916/f815777e-18fd-4597-93a5-6a7b04f851a6)

**Comment by MRDHR** [comment]
I am currently installing in the windows environment and import your sdk into my project.

**Comment by ybd-project** [comment]
We have not yet implemented the ability to display a confirmation message to automatically download yt-dlp, etc.
We hope to release a version with this functionality today, if possible.

**Comment by ybd-project** [comment]
I have tested the ability to display a confirmation message when installing this package from npm, but it fails, so I have settled on the "user sets environment variable" result.
The name of the environment variable is "FLUENT_YTDLP_NO_AUTO_DOWNLOAD".
As mentioned in the README, if you want to specify your own binary path, use "setBinaryPath()".

**Comment by MRDHR** [comment]
OK, I'll try to install version 1.3.0.
I'm using spawn to execute yt-dlp commands directly, and the child threads are poorly managed. I hope your sdk will have a good experience.

I am from China, and the above words are translated by the translator.

**Comment by ybd-project** [comment]
私もこのパッケージが良い結果になることを望んでいます。
他にもバグ等がありましたら報告してください！

ありがとうございました！

**Comment by ybd-project** [comment]
I too hope this package turns out well.
Please report any other bugs, etc!

Thank you very much!
