### ISSUE TITLE
MergeOutputFormatという方法ではパラメータを置くことができない.

### ISSUE THREAD

**Issue by MRDHR** [ybd-project/node-fluent-ytdlp#2]
## 前提

- この問題の報告が**まだIssuesにない**ことを確認しています。 =>
- **この問題がこのAPIによるもの**と確認できています。=>
- 
MergeOutputFormatという方法ではパラメータを置くことができない.
Yt-dlpの公式文書には，MergeOutputFormatメソッドの後に，mp 4，movなどのパラメータを加える.

## 動作環境

Node.jsのバージョン：
OSの種類：

## Node.jsのログ

```
Log...
```

## APIのコード

```
   ytdlp.format('bestvideo[ext=mp4]+bestaudio[ext=m4a]/best[ext=mp4]/best')
            .preferFreeFormats()
            .noCheckCertificates()
            .downloadSections('*' + startTime + '-' + endTime)
            .restrictFilenames()
            .mergeOutputFormat("mp4")
            .output(outtmpl)
```

## バグに関する詳細
![image](https://github.com/ybd-project/node-fluent-ytdlp/assets/5576916/22454ed0-35e8-491b-aa1f-a0481019bbca)
![image](https://github.com/ybd-project/node-fluent-ytdlp/assets/5576916/c7aec2cb-8711-4f47-89fe-94a2582ef23d)

**Comment by MRDHR** [comment]
私のもとの書き方と比較して，フルーエントを使ってずいぶん簡素化した
新しい実現方式
![image](https://github.com/ybd-project/node-fluent-ytdlp/assets/5576916/56106b97-a3d7-4b90-8dd3-b9b3983b022a)

古い=の実現方式
![image](https://github.com/ybd-project/node-fluent-ytdlp/assets/5576916/1ccf9554-edf4-4f12-bb54-811fe3194f69)

私が一般的に使っている言語はjavaなのでJavaScriptベースは非常に悪いです

**Comment by ybd-project** [comment]
Issueありがとうございます。
この問題は、完全に私のミスなのですぐに修正します。

**Comment by ybd-project** [comment]
この問題を修正したv1.3.1を公開しました。
mergeOutputFormatが正常に機能しない場合は、さらにissueで報告してください。

**Comment by MRDHR** [comment]
I still have a little bit of advice, which I hope can be adopted.
For example: get-title, the input parameter of yt-dlp, has no parameters. In your current implementation, you need to set otherOptions ({getTitle: ""}).
Whether otherOptions can cancel the key-value pair, only pass in the key value of getTitle.
![image](https://github.com/ybd-project/node-fluent-ytdlp/assets/5576916/4d1d6918-757b-492c-8e33-ac669bb331bc)

**Comment by MRDHR** [comment]
ここでもう1つの問題があるが，なぜstdoutが読み込んだbytesはすべてのログを含むのか？
普通の論理では最後の行だけではいけませんか？

![image](https://github.com/ybd-project/node-fluent-ytdlp/assets/5576916/78199257-1a93-4c6c-b919-b6f7fc2ca83d)

**Comment by ybd-project** [comment]
提案・報告ありがとうございます。
まず、get-titleについてですが、このオプションはyt-dlpでは冗長に指定されているため個別のgetTitle関数を実装する予定はありません。現時点での解決策はprint("title");（--print title）を指定することです。
必要であればotherOptionsの値にnullを設定することでパラメータを設定しないようにすることもできます。（まだ実装されていません。）

次に、stdoutのログについてですが、これはspawnに任せているため、私からは何ともいうことはできません。
